export const REFERENCE_ANIMATION_PRESETS = [
  {id: '01_slide_up_lines', label: "Deslizar hacia arriba (Líneas)", animation: 'slide-up', unit: 'lines' as const},
  {id: '02_slide_up_words', label: "Deslizar hacia arriba (Palabras)", animation: 'slide-up', unit: 'words' as const},
  {id: '03_slide_up_letters', label: "Deslizar hacia arriba (Letras)", animation: 'slide-up', unit: 'letters' as const},
  {id: '04_slide_down_lines', label: "Deslizar hacia abajo (Líneas)", animation: 'slide-down', unit: 'lines' as const},
  {id: '05_slide_down_words', label: "Deslizar hacia abajo (Palabras)", animation: 'slide-down', unit: 'words' as const},
  {id: '06_slide_down_letters', label: "Deslizar hacia abajo (Letras)", animation: 'slide-down', unit: 'letters' as const},
  {id: '07_slide_left_lines', label: "Deslizar a la izquierda (Líneas)", animation: 'slide-left', unit: 'lines' as const},
  {id: '08_slide_right_lines', label: "Deslizar a la derecha (Líneas)", animation: 'slide-right', unit: 'lines' as const},
  {id: '09_slide_left_words', label: "Deslizar a la izquierda (Palabras)", animation: 'slide-left', unit: 'words' as const},
  {id: '10_slide_right_words', label: "Deslizar a la derecha (Palabras)", animation: 'slide-right', unit: 'words' as const},
  {id: '11_fade_simple', label: "Desvanecimiento simple", animation: 'fade-simple', unit: 'whole' as const},
  {id: '12_fade_soft', label: "Desvanecimiento suave", animation: 'fade-soft', unit: 'whole' as const},
  {id: '13_blur_fade', label: "Desenfoque y fundido", animation: 'blur-fade', unit: 'whole' as const},
  {id: '14_scale_a', label: "Escala (A)", animation: 'scale-a', unit: 'whole' as const},
  {id: '15_scale_b', label: "Escala (B)", animation: 'scale-b', unit: 'whole' as const},
  {id: '16_scale_letters', label: "Escala (Letras)", animation: 'scale', unit: 'letters' as const},
  {id: '17_tracking_reveal_simple', label: "Revelación de seguimiento (Simple)", animation: 'tracking-simple', unit: 'letters' as const},
  {id: '18_tracking_reveal_elastic', label: "Seguimiento de Revelación (Elástico)", animation: 'tracking-elastic', unit: 'letters' as const},
  {id: '19_reveal_soft', label: "Revelación suave", animation: 'reveal-soft', unit: 'whole' as const},
  {id: '20_reveal_bounce', label: "Revelación con rebote", animation: 'reveal-bounce', unit: 'whole' as const},
  {id: '21_reveal_flip', label: "Revelación al voltear", animation: 'flip', unit: 'whole' as const},
  {id: '22_blurry_reveal_letters', label: "Revelación borrosa (Letras)", animation: 'blur', unit: 'letters' as const},
  {id: '23_blur_reveal_words', label: "Revelar con desenfoque (Palabras)", animation: 'blur', unit: 'words' as const},
  {id: '24_blurry_reveal_random', label: "Revelación borrosa (Aleatoria)", animation: 'blur-random', unit: 'letters' as const},
  {id: '25_blur_reveal_chaotic', label: "Desenfoque revelar (caótica)", animation: 'chaotic', unit: 'letters' as const},
  {id: '26_letter_deletion', label: "Eliminación de letras", animation: 'delete-letters', unit: 'letters' as const},
  {id: '27_letters_ascending', label: "Letras en ascenso", animation: 'ascend', unit: 'letters' as const},
] as const;
