import type {Caption, TikTokPage} from '@remotion/captions';
import type {CustomBrollItem, CaptionGroupStyleOverride, MotionGraphicItem} from './types';

/** The editor's four-caption groups are also the exported pages. No page spans a silent gap. */
export const captionGroups = (captions: Caption[]) => {
  const groups = [];
  for (let index = 0; index < captions.length; index += 4) {
    const slice = captions.slice(index, index + 4);
    groups.push({startIndex:index,endIndex:index+slice.length,startMs:slice[0].startMs,
      endMs:slice[slice.length-1].endMs,text:slice.map(c=>c.text.trim()).join(' ')});
  }
  return groups;
};
export const captionPages = (captions:Caption[]):TikTokPage[] => captionGroups(captions).map(group=>({
  text:group.text,startMs:group.startMs,durationMs:group.endMs-group.startMs,
  tokens:captions.slice(group.startIndex,group.endIndex).map(c=>({text:c.text,fromMs:c.startMs,toMs:c.endMs})),
}));
export const clampProgress = (value:number) => Math.max(0,Math.min(1,value));
/** Seek-safe, clock-independent animation. Distances are relative to the text size. */
export const textEntrance = (elapsed:number, enabled=true, fromRight=false) => {
  const progress = enabled ? clampProgress(elapsed/.28) : 1;
  const eased = 1-Math.pow(1-progress,3);
  return {opacity:enabled ? clampProgress(elapsed/.14) : 1,x:fromRight ? (1-eased)*1.8 : 0,scale:enabled ? .96+.04*eased : 1};
};
export const wordPulse = (elapsed:number, active:boolean, enabled:boolean) =>
  active && enabled ? 1+.08*Math.sin(Math.PI*clampProgress(elapsed/.22)) : 1;

// Automatic clips must render the spoken text, not fall back to a static title
// plus a second caption layer. This also covers already-saved automatic clips.
export const brollOwnsAnimatedText = (broll:CustomBrollItem) => !broll.templateId && Boolean(broll.autoGenerated || broll.dualFont || broll.textEffect==='editorial');
export const brollTextFontSize = (broll:CustomBrollItem) => Math.max(28,Math.min(160,broll.fontSize || 58));
export const resolveBrollCaptionStyle = (broll:CustomBrollItem,style:Omit<CaptionGroupStyleOverride,'id'|'startMs'|'endMs'>):CustomBrollItem => {
  if (!(broll.inheritCaptionStyle ?? broll.autoGenerated)) return broll;
  return {...broll,fontFamily:style.captionFontFamily,fontSize:style.fontSize,accentColor:style.accentColor,
    ...(style.dualFontEnabled && broll.dualFont ? {topFontFamily:style.topFontFamily,bottomFontFamily:style.bottomFontFamily} : {})};
};
/** Keep exact spoken timing: do not extend short words, duplicate a first page in gaps, or overwrite manual text. */
export const brollTextPage = (broll:CustomBrollItem,captions:Caption[],time:number) => {
  if (time<broll.start || time>=broll.start+broll.duration) return null;
  const manual = broll.textSource==='manual';
  const source = manual ? [] : captions.filter(c=>c.endMs>broll.start*1000 && c.startMs<(broll.start+broll.duration)*1000);
  const words = source.flatMap(c=>{
    const tokens=c.text.trim().split(/\s+/).filter(Boolean);
    return tokens.map((text,index)=>({text,start:Math.max(broll.start,(c.startMs+(c.endMs-c.startMs)*index/tokens.length)/1000),
      end:Math.min(broll.start+broll.duration,(c.startMs+(c.endMs-c.startMs)*(index+1)/tokens.length)/1000)}));
  }).filter(w=>w.end>w.start);
  if (!source.length && (manual || !captions.length)) {
    const tokens=(broll.brollText || broll.brollHeadline || '').trim().split(/\s+/).filter(Boolean);
    words.push(...tokens.map((text,index)=>({text,start:broll.start+broll.duration*index/tokens.length,end:broll.start+broll.duration*(index+1)/tokens.length})));
  }
  for(let index=0;index<words.length;index+=4) {
    const page=words.slice(index,index+4);
    if(time>=page[0].start && time<page[page.length-1].end) return {words:page,start:page[0].start,end:page[page.length-1].end};
  }
  return null;
};

export const motionHidesCaptions = (item:MotionGraphicItem) => item.displayMode !== 'floating' || Boolean(item.dualFont && item.textSource!=='manual');
/** Automatic motion follows current speech; explicitly edited text stays manual. */
export const resolveMotionText = (item:MotionGraphicItem,captions:Caption[],time:number):MotionGraphicItem => {
  let resolved=item;
  if (item.textSource !== 'manual' && captions.length && item.type === '3d-scene') {
    const page=brollTextPage({id:item.id,src:'',type:'image',start:item.start,duration:item.duration},captions,time);
    const title=page?.words.map(word=>word.text).join(' ') || '';
    const objectContext=captions.filter(c=>c.endMs>item.start*1000 && c.startMs<(item.start+item.duration)*1000).map(c=>c.text.trim()).join(' ');
    resolved={...item,title,subtitle:'',highlightWord:page?.words.at(-1)?.text,textPageStart:page?.start,objectContext};
  }
  const normalized=(text:string) => text.replace(/[\[\]]/g,'').trim().replace(/\s+/g,' ').toLowerCase();
  return resolved.subtitle && normalized(resolved.subtitle) === normalized(resolved.title)
    ? {...resolved,subtitle:''} : resolved;
};
