import type { Caption } from '@remotion/captions';
import type { CaptionStyleId } from './presets';

export type BrollWord = {
  text: string;
  start: number;
  end: number;
};

export type BrollEvent = {
  src: string;
  start: number;
  end: number;
  text: string;
  words: BrollWord[];
};

export type ZentryVideoProps = {
  src: string;
  captions: Caption[];
  styleId: CaptionStyleId;
  accentColor: string;
  fontSize: number;
  captionFontFamily: string;
  captionFontWeight: number;
  captionItalic: boolean;
  captionDualFont?: boolean;
  captionTopFontFamily?: string;
  captionBottomFontFamily?: string;
  captionAlign: 'left' | 'center' | 'right';
  shadow: boolean;
  popAnimation: boolean;
  captionPositionX: number;
  captionPositionY?: number;
  captionGroupStyles?: CaptionGroupStyleOverride[];
  motionGraphicsItems?: MotionGraphicItem[];
  keepSegments: { start:number; end:number; src?:string; clipVolume?:number; clipMuted?:boolean; brightness?:number; contrast?:number; saturation?:number; sharpness?:number; processedAudioSrc?:string }[];
  hookLeadText: string;
  hookMainText: string;
  hookPositionX: number;
  hookPositionY: number;
  hookLeadFontFamily: string;
  hookMainFontFamily: string;
  hookLeadFontSize: number;
  hookMainFontSize: number;
  hookLeadDuration: number;
  hookMainDuration: number;
  hookStyle: 'viro' | 'impact' | 'editorial' | 'clean' | 'motivacional' | 'instagram' | 'boldcaps';
  zoomPunch: boolean;
  motionGraphics: boolean;
  overlaySrc: string | null;
  brollEvents: BrollEvent[];
  brollFontFamily: string;
  brollTransition: 'fade' | 'slide' | 'zoom' | 'flash' | 'glitch' | 'spin';
  brollTypingSoundSrc: string | null;
  volume: number;
  sfxSrc: string | null;
  manualSfxClips?: Array<{ id:string; src:string; start:number; volume:number }>;
  customBrolls?: CustomBrollItem[];
  showWatermark?: boolean;
  hookSfxSrc?: string | null;
  contextualSfxEvents?: Array<{
    id: string;
    timeSec: number;
    sfxSrc: string;
    label: string;
    volume: number;
  }>;
  zentryItems?: ZentryTemplateItem[];
  sfxVolumeMultiplier?: number;
  sfxTimeOverrides?: Record<string, number>;
  musicTracks?: Array<{ id:string; src:string; start:number; duration:number; sourceStart:number; volume:number; playbackRate?:number }>;
};

export type CaptionGroupStyleOverride = {
  id: string;
  startMs: number;
  endMs: number;
  styleId: CaptionStyleId;
  accentColor: string;
  fontSize: number;
  captionFontFamily: string;
  captionFontWeight: number;
  captionItalic: boolean;
  dualFontEnabled?: boolean;
  topFontFamily?: string;
  bottomFontFamily?: string;
  captionAlign: 'left' | 'center' | 'right';
  shadow: boolean;
  popAnimation: boolean;
  positionX: number;
  positionY: number;
};

export type ZentryTemplateCategory = 'subtitles' | 'hooks' | 'typography' | 'broll' | 'motion-graphics';

export type ZentryTemplateItem = {
  fontSize?: number;
  textScale?: number;
  positionX?: number;
  positionY?: number;
  id: string;
  presetId: string;
  category: ZentryTemplateCategory;
  brollSubcategory?: 'top' | 'center' | 'bottom';
  fontVariant?: 'montserrat' | 'playfair';
  start: number; // in seconds
  duration: number; // in seconds
  sfxEnabled: boolean;
  sfxVolume: number; // 0 to 1
  sfxId: string;
  offsetFrames: number;
  sfxLinked: boolean;
  customProps?: Record<string, any>;
};

export type BrollTemplateStyle = 'white-minimal' | 'red-impact' | 'black-oled' | 'video' | 'image';
export type BrollTransitionEffect = 'whip-pan' | 'zoom-punch' | 'film-burn' | 'rgb-glitch' | 'smooth-fade' | 'slide-up' | 'slide-down' | 'fade' | 'none';
export type BrollTextEffect = 'spring' | 'typewriter' | 'glow' | 'none' | 'editorial';

export type CustomBrollItem = {
  inheritCaptionStyle?: boolean;
  textSource?: 'manual' | 'transcript';
  id: string;
  src: string;
  type: 'video' | 'image';
  start: number;
  duration: number;
  title?: string;
  brollStyle?: BrollTemplateStyle;
  brollHeadline?: string;
  brollText?: string;
  icon3d?: string;
  transitionDirection?: 'slide-up' | 'slide-left' | 'slide-right';
  transitionIn?: BrollTransitionEffect;
  transitionOut?: BrollTransitionEffect;
  templateId?: string;
  templateFontVariant?: 'montserrat' | 'playfair';
  templateSfxEnabled?: boolean;
  fontFamily?: string;
  fontSize?: number;
  textColor?: string;
  accentColor?: string;
  backgroundColor?: string;
  textEffect?: BrollTextEffect;
  dualFont?: boolean;
  topFontFamily?: string;
  bottomFontFamily?: string;
  sfxSrc?: string | null;
  sfxVolume?: number;
  sfxEnabled?: boolean;
  autoGenerated?: boolean;
};

export type MotionGraphic3DStyle =
  | 'editorial-bw'
  | 'cinematic-black'
  | 'photoreal-3d'
  | 'collage-vintage';

export type MotionGraphicCardStyle = 'apple' | 'neon' | 'editorial';

export type MotionGraphicStyle = MotionGraphic3DStyle | MotionGraphicCardStyle;

export type MotionGraphicCardType =
  | '3d-scene'
  | 'stat'
  | 'notif'
  | 'apps'
  | 'checklist'
  | 'progress'
  | 'quote'
  | 'alert'
  | 'pill';

export type MotionGraphicCardTheme = 'white' | 'red' | 'black' | 'yellow' | 'neon' | 'glass';
export type WordAnimationMode = 'spring' | 'typewriter' | 'elevation3d' | 'glow';
export type MotionEntranceTransition = 'slide-up' | 'slide-left' | 'slide-right' | 'pop-3d';

export type MotionGraphicItem = {
  objectSet?: 'auto' | 'technology' | 'finance' | 'conversation' | 'learning' | 'growth' | 'icon' | 'off';
  objectContext?: string;
  fontSize?: number;
  dualFont?: boolean;
  topFontFamily?: string;
  bottomFontFamily?: string;
  textPageStart?: number;
  textSource?: 'manual' | 'transcript';
  id: string;
  type: MotionGraphicCardType;
  style: MotionGraphicStyle;
  start: number;
  duration: number;
  title: string;
  value?: string;
  subtitle?: string;
  highlightWord?: string;
  bgVideoUrl?: string;
  positionX?: number;
  positionY?: number;
  displayMode?: 'full' | 'floating';
  sfxSrc?: string;
  objects3d?: string[];
  category?: string;
  highlightTemplate?: 'red' | 'white' | 'yellow' | 'neon' | 'glass';
  cardTheme?: MotionGraphicCardTheme;
  wordAnimationMode?: WordAnimationMode;
  icon3d?: string;
  entranceTransition?: MotionEntranceTransition;
};
