import type {CustomBrollItem, MotionGraphicItem, ZentryTemplateItem} from './types';

export type VisibleVisualLayer = {kind:'broll' | 'motion' | 'zentry'; id:string} | null;

const finite = (value:number | undefined,fallback:number,min:number,max:number) =>
  Number.isFinite(value) ? Math.max(min,Math.min(max,value!)) : fallback;

/** Relative canvas offsets preserve legacy template placement at 50/50, scale 1. */
export const getZentryLayout = (item:ZentryTemplateItem,width:number,height:number) => {
  const x=finite(item.positionX,50,0,100);
  const y=finite(item.positionY,50,0,100);
  const scale=finite(item.textScale,1,.25,2.5);
  return {transform:`translate(${(x-50)*width/100}px, ${(y-50)*height/100}px) scale(${scale})`,transformOrigin:'center center'};
};

/** Keep the editor preview and Remotion export on the same single foreground scene. */
export const getVisibleVisualLayer = (
  time:number,
  brolls:CustomBrollItem[],
  motionItems:MotionGraphicItem[],
  zentryItems:ZentryTemplateItem[],
):VisibleVisualLayer => {
  const candidates = [
    ...brolls.map((item) => ({kind:'broll' as const,id:item.id,start:item.start,end:item.start+item.duration,priority:item.autoGenerated ? 0 : 1})),
    ...motionItems.map((item) => ({kind:'motion' as const,id:item.id,start:item.start,end:item.start+item.duration,priority:1})),
    // Caption presets are text replacements, not foreground scenes. They must
    // not hide an existing B-roll/motion simply because their group starts later.
    ...zentryItems.map((item) => ({kind:'zentry' as const,id:item.id,start:item.start,end:item.start+item.duration,priority:item.category === 'subtitles' ? -1 : 1})),
  ].filter((item) => time >= item.start && time < item.end);
  candidates.sort((a,b) => b.priority-a.priority || b.start-a.start || b.end-a.end || b.id.localeCompare(a.id));
  return candidates[0] ? {kind:candidates[0].kind,id:candidates[0].id} : null;
};

/** Older short Hero Split clips saved the entire phrase twice. Keep both lines distinct. */
export const getZentryVisualProps = (item:ZentryTemplateItem):Record<string, unknown> => {
  const props = item.customProps || {};
  if (item.presetId !== 'motion_01_hero_split' || typeof props.title !== 'string' || typeof props.subtitle !== 'string') return props;
  if (props.title.trim().toLocaleLowerCase() !== props.subtitle.trim().toLocaleLowerCase()) return props;
  const words = props.title.trim().split(/\s+/).filter(Boolean);
  if (words.length < 2) return {...props,subtitle:''};
  const splitAt = Math.ceil(words.length / 2);
  return {...props,title:words.slice(0,splitAt).join(' '),subtitle:words.slice(splitAt).join(' ')};
};
